services:

  sqldata:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5301:5432"
    volumes:
      - "./docker/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql"
      - "donut-sqldata:/var/lib/postgresql/data"

  nosqldata:
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "5302:27017"
    volumes:
      - "donut-nosqldata:/data/db"

  cachedata:
    ports:
      - "5303:6379"

  messagequeue:
    ports:
      - "5672:5672"
      - "15672:15672"

  vault:
    command: vault server -dev -dev-listen-address="0.0.0.0:8200"
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root-token
    volumes:
      - ./docker/vault/config:/vault/config
    privileged: true
    cap_add:
      - IPC_LOCK

  vault-init:
    volumes:
      - ./docker/vault/vault-init.sh:/vault-init.sh
    depends_on:
      - vault
    restart: "no"
    entrypoint: sh -c "/vault-init.sh"

  keycloak:
    command: "start-dev --import-realm"
    environment:
      - "KC_BOOTSTRAP_ADMIN_USERNAME=admin"
      - "KC_BOOTSTRAP_ADMIN_PASSWORD=admin"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://sqldata:5432/keycloak"
      - "KC_DB_USERNAME=admin"
      - "KC_DB_PASSWORD=admin"
    ports:
      - "5501:8080"
    volumes:
      - "./docker/keycloak/somesandwich-donut-realm.json:/opt/keycloak/data/import/somesandwich-donut-realm.json"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    ports:
      - "5101:80"

  link-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    ports:
      - "5102:80"

volumes:
  donut-sqldata:
    external: false
  donut-nosqldata:
    external: false
  donut-cachedata:
    external: false
