version: '3.9'

services:

  sqldata:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5301:5432"
    volumes:
      - "./docker/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql"
      - "donut-sqldata:/var/lib/postgresql/data"

  nosqldata:
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "5302:27017"
    volumes:
      - "donut-nosqldata:/data/db"

  fluentd:
    volumes:
      - "./docker/fluentd/conf:/fluentd/etc"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    volumes:
      - "donut-efkdata:/usr/share/elasticsearch/data:Z"

  kibana:
    ports:
      - "5601:5601"

  zipkin:
    ports:
      - "5401:9411"

  dapr-dashboard:
    command: ["--docker-compose=true",
      "--components-path=/components",
      "--config-path=/configuration",
      "--docker-compose-path=/docker-compose.yml"
      ]
    ports:
      - "5402:8080"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
      - "./docker-compose.yml/:/docker-compose.yml"

  keycloak:
    command: "start-dev --import-realm"
    environment:
      - "KC_BOOTSTRAP_ADMIN_USERNAME=admin"
      - "KC_BOOTSTRAP_ADMIN_PASSWORD=admin"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://sqldata:5432/keycloak"
      - "KC_DB_USERNAME=admin"
      - "KC_DB_PASSWORD=admin"
    ports:
      - "5501:8080"
    volumes:
      - "./docker/keycloak/somesandwich-donut-realm.json:/opt/keycloak/data/import/somesandwich-donut-realm.json"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5101:80"
      - "50001:50001"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: identity-api

  identity-api-dapr:
    command: ["./daprd",
      "-app-id", "identity-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",.
      "-config", "/configuration/donut-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  link-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5102:80"
      - "50002:50001"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: link-api

  link-api-dapr:
    command: ["./daprd",
      "-app-id", "link-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/donut-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
volumes:
  donut-sqldata:
    external: false
  donut-nosqldata:
    external: false
  donut-efkdata:
    external: false
