version: '3.4'

services:
  somesandwich.donut.identity:
    image: ${DOCKER_REGISTRY-}somesandwichdonutidentity
    build:
      context: .
      dockerfile: src/SomeSandwich.Donut.Identity/Dockerfile
