version: '3.9'

services:

  postgres:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5301:5432"
    volumes:
      - donut-sqldata:/var/lib/postgresql/data

  zipkin:
    ports:
      - "5401:9411"

  dapr-dashboard:
    command: ["--docker-compose=true",
      "--components-path=/components",
      "--config-path=/configuration",
      "--docker-compose-path=/docker-compose.yml"
      ]
    ports:
      - "5402:8080"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
      - "./docker-compose.yml/:/docker-compose.yml"

  keycloak:
    command: "start-dev --import-realm"
    environment:
      - "KC_BOOTSTRAP_ADMIN_USERNAME=admin"
      - "KC_BOOTSTRAP_ADMIN_PASSWORD=admin"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://postgres:5432/"
      - "KC_DB_USERNAME=admin"
      - "KC_DB_PASSWORD=admin"
    ports:
      - "5501:8080"
    volumes:
      - "./docker/keycloak/somesandwich-donut-realm.json:/opt/keycloak/data/import/somesandwich-donut-realm.json"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5101:80"
      - "50001:50001"

  identity-api-dapr:
    command: ["./daprd",
      "-app-id", "identity-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/donut-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

volumes:
  donut-sqldata:
    external: false
