version: '3.9'

services:

  dapr-dashboard:
    command: ["--docker-compose=true",
      "--components-path=/components",
      "--config-path=/configuration",
      "--docker-compose-path=/docker-compose.yml"
      ]
    ports:
      - "8080:8080"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
      - "./docker-compose.yml/:/docker-compose.yml"

  zipkin:
    ports:
      - "5411:9411"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5101:80"
      - "50001:50001"

  identity-api-dapr:
    command: ["./daprd",
      "-app-id", "identity-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/donut-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
