services:

  sqldata:
    image: postgres:17-alpine

  nosqldata:
    image: mongo:latest

  cachedata:
    image: redis:alpine

  messagequeue:
    image: rabbitmq:4-management-alpine

  vault:
    image: hashicorp/vault:latest

  vault-init:
    image: hashicorp/vault:latest

  keycloak:
    image: quay.io/keycloak/keycloak:latest

  identity-api:
    image: ${REGISTRY:-donut}/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/SomeSandwich.Donut.Identity/Dockerfile
    depends_on:
      - keycloak

  link-api:
    image: ${REGISTRY:-donut}/link.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/SomeSandwich.Donut.Link/Dockerfile
    depends_on:
      - nosqldata
      - cachedata
      - messagequeue
