version: '3.4'

services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/Gateways/Gateway.API/Dockerfile
    networks:
      - donut-network

  eureka:
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"
    networks:
      - donut-network


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    networks:
      - donut-network


  link.api:
    image: ${DOCKER_REGISTRY-}linkapi
    build:
      context: .
      dockerfile: src/Services/Link/Link.API/Dockerfile
    networks:
      - donut-network

networks:
  donut-network:
    name: donut-network
    driver: bridge
