version: '3.4'

services:
  somesandwich.donut.identity:
    image: ${DOCKER_REGISTRY-}somesandwichdonutidentity
    build:
      context: .
      dockerfile: src/SomeSandwich.Donut.Identity/Dockerfile

  somesandwich.donut.link:
    image: ${DOCKER_REGISTRY-}somesandwichdonutlink
    build:
      context: .
      dockerfile: src/SomeSandwich.Donut.Link/Dockerfile

