{
 "title": "Observability Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(service_namespace)"
    }
   },
   { "name": "service", "label": "Service", "query": { "query": "label_values(service_name)" } },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{service_name=\"$service\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{service_name=\"$service\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pool",
    "query": {
     "query": "label_values(jvm_buffer_memory_used_bytes{service_name=\"$service\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  increase (\r\n    http_server_request_duration_seconds_count{service_name=\"$service\"}[$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "HTTP Request Status Codes Ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\r\n  label_replace (\r\n    increase (\r\n      http_server_request_duration_seconds_count{service_name=\"$service\"}[$__range]\r\n    ),\r\n    \"http_response_status_code\",\r\n    \"Unknown\",\r\n    \"http_response_status_code\",\r\n    \"\"\r\n  )\r\n)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_route, http_request_method) (\r\n  rate (\r\n    http_server_request_duration_seconds_count{service_name=\"$service\"}[5m]\r\n  )\r\n)",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (http_route, http_request_method) (\r\n  increase(\r\n    http_server_request_duration_seconds_count{\r\n      service_name=\"$service\", \r\n      http_response_status_code=~\"2..|3..\"\r\n    }[$__range]\r\n  )\r\n)"
    },
    {
     "expr": "sum by (http_route, http_request_method) (\r\n  increase(\r\n    http_server_request_duration_seconds_count{\r\n      service_name=\"$service\", \r\n      http_response_status_code=~\"4..|5..\"\r\n    }[$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_route, http_request_method) (\r\n  increase (\r\n    http_server_request_duration_seconds_sum{service_name=\"$service\"}[$__range]\r\n  )\r\n)\r\n/\r\nsum by (http_route, http_request_method) (\r\n  increase (\r\n    http_server_request_duration_seconds_count{service_name=\"$service\"}[$__range]\r\n  )\r\n)",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "ClassLoading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Class Current Loading",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_class_count{service_name=\"$service\"}"
      }
     ]
    },
    {
     "title": "Total Class Loaded",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_class_loaded_total{service_name=\"$service\"}"
      }
     ]
    }
   ]
  },
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds) / 3600"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "JVM Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Pool(Heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service_name=\"$service\", id=~\"$jvm_memory_pool_heap\"}"
      },
      {
       "expr": "jvm_memory_committed_bytes{service_name=\"$service\", id=~\"$jvm_memory_pool_heap\"}"
      },
      {
       "expr": "jvm_memory_max_bytes{service_name=\"$service\", id=~\"$jvm_memory_pool_heap\"}"
      }
     ]
    },
    {
     "title": "JVM Memory Pool(Non-Heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service_name=\"$service\", id=~\"$jvm_memory_pool_nonheap\"}"
      },
      {
       "expr": "jvm_memory_committed_bytes{service_name=\"$service\", id=~\"$jvm_memory_pool_nonheap\"}"
      },
      {
       "expr": "jvm_memory_max_bytes{service_name=\"$service\", id=~\"$jvm_memory_pool_nonheap\"}"
      }
     ]
    },
    {
     "title": "JVM Duration Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "rate(jvm_gc_duration_seconds_sum[5m])"
      }
     ]
    },
    {
     "title": "Buffer Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service_name=\"$service\", id=~\"$jvm_buffer_pool\"}"
      }
     ]
    },
    {
     "title": "JVM Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(jvm_thread_count{service_name=\"$service\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total Time For Garbage Collection Per Service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "targets": [
      {
       "expr": "jvm_gc_duration_seconds_sum{service_name=\"$service\"}"
      }
     ]
    }
   ]
  },
  { "title": "CPU Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "service_name" },
  {
   "title": "CPU Usage Per Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total" },
    {
     "expr": "jvm_class_loaded_total{service_name=\"$service\"}"
    }
   ]
  },
  {
   "title": "CPU Ratio Used Per Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio"
    }
   ]
  },
  {
   "title": "JVM CPU Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_cpu_count{service_name=\"$service\"}"
    }
   ]
  },
  {
   "title": "Total CPU Usage Rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "Top 5 Rate Using CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(5, rate(process_cpu_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "Memory Used After Last Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_after_last_gc_bytes{service_name=\"$service\", id=~\"$jvm_memory_pool_heap\"}"
    }
   ]
  },
  { "title": "Memory Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Memory Usage Per Service (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by(service_name) (jvm_memory_used_bytes{service_name=\"$service\"}) / 1048576"
    }
   ]
  },
  {
   "title": "Memory commiited (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by(service_name) (jvm_memory_committed_bytes{service_name=\"$service\"}) / 1048576"
    }
   ]
  },
  {
   "title": "Memory limit (Mb)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (jvm_memory_limit_bytes{service_name=\"$service\"}) / 1048576"
    }
   ]
  },
  {
   "title": "Prometheus Memory Used (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes [5m]) / 1048576"
    }
   ]
  },
  {
   "title": "Database Connection Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true
  },
  {
   "title": "Max Connection Allowed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    { "expr": "db_client_connections_max" }
   ]
  },
  {
   "title": "Number Of Connection In Use",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "repeat": "job",
   "targets": [
    { "expr": "db_client_connections_usage" }
   ]
  }
 ]
}