apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: donut
spec:
  tracing:
    samplingRate: "1"
    stdout: true
    otel:
      endpointAddress: "localhost:4317"
      isSecure: false
      protocal: grpc
